# Week 5: Scaling techniques

Here we begin thinking about more automated techniques for analyzing texts. And there are a bunch of additional considerations we now need to bring to mind. These considerations have sparked significant debates... and the matter is by no means settled.

So what is at stake here? In weeks to come, we will be studying various techniques to 'classify,' 'position' or 'score' texts based on their features. The success of these techniques depends on their suitability to the question at hand but also on higher-level questions about meaning. In short, we have to ask ourselves: is there a way we can access the underlying processes governing the generation of text? Is meaning governed by a set of structural processes? And can we derive 'objective' measures of the contents of any given text?

The readings by @grimmer_machine_2021, @denny_text_2018, and @goldenstein_analyzing_2019 (as well as the response and replies by @nelson_measure_2019 and @goldenstein_quest_2019) will be required reading for Flexible Learning Week. 

- @grimmer_machine_2021
- @grimmer_text_2013
- @denny_text_2018

- @goldenstein_analyzing_2019
  - @nelson_measure_2019
  - @goldenstein_quest_2019
  
The substantive focus of this week are a set of readings that all employ different types of "scaling" or "low-dimensional document embedding" techniques. The article by @lowe_understanding_2008 provides a technical overview of the "wordfish" algorithm and its uses in a political science contexts. The article by @kluver_measuring_2009 also uses "wordfish" in a different way---to measure the "influence" of interest groups. The response to this article by @bunea_quantitative_2015 and subsequent reply by @kluver_promises_2015 helps illuminate some of the debates around these questions. 

Questions:

1. What assumptions underlie scaling models of text?; What is latent in a text and who decides?
2. What might scaling be useful for outside of estimating ideological position from text?

**Required reading**:

- @slapin_scaling_2008
- @kaneko_estimating_2021
- @kluver_measuring_2009
  - @bunea_quantitative_2015
  - @kluver_promises_2015

**Further reading**:

- @benoit_crowd-sourced_2016
- @laver_extracting_2003
- @lowe_understanding_2008
- @schwemmer_methodological_2020
- @kaneko_estimating_2021

**Slides**:

- Week 5 [Slides](https://docs.google.com/presentation/d/1oG0JBlnRaOZ1kJIkzM13kmEpM1R29mFE_50QAZnv0bQ/edit?usp=sharing)